name: Testing if my bootstrap.sh script works and does not give errors
on: [push]
jobs:
  Test-Installation-Action:
    runs-on: macos-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - run: echo "The name of this branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v2

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

    #   - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: give boostrap script execute permissions
        run: | 
          chmod +x ${{github.workspace}}/bootstrap.sh
      
      - name: Run bootstrap.sh script 
        run: ./bootstrap.sh

      
